### ISSUE TITLE
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Endpoints]  with name: [null]  in namespace: [null]  failed.

### ISSUE THREAD

**Issue by patpatpat123** [piomin/sample-spring-microservices-kubernetes#3]
Hello,

Thank you for this tutorial.
When starting the same on my Kubernetes cluster, I am seeing this:

```
ERROR [,93eaa38a2ce2dd76,93eaa38a2ce2dd76,true] 47 --- [   scheduling-1] o.s.c.k.d.KubernetesCatalogWatch         : Error watching Kubernetes Services

io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Endpoints]  with name: [null]  in namespace: [null]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64) ~[kubernetes-client-4.10.3.jar!/:na]

```

```
Caused by: java.net.ConnectException: Failed to connect to /1xx.1xx.0.1:443
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:265) ~[okhttp-3.14.9.jar!/:na]
```

Would you know why please?

**Comment by piomin** [comment]
fixed

**Comment by patpatpat123** [comment]
Hello @piomin ,

Thank you for looking into this after all those years

**Comment by patpatpat123** [comment]
Could you please link the relevant PR as well?
That way, this issue is fully documented
